name: whwb
version: 1

cron:
  - description: backup commit
    url: admin/backup
    schedule: "30 3 * * *"
    timezone: Beijing
  - description: backup status
    url: admin/backup_status
    schedule: "10 8-22/4 * * *"
    timezone: Beijing